# Exercises (Optional)

These exercises are not required to complete however are good to do for practice. (Not to be submitted on git)

These exercises are a mix of Python and pandas/EDA practice. Most should be no more than a few lines of code! 

In [3]:
import numpy as np
# here is a Python list:

a = [1, 2, 3, 4, 5, 6]
print(a)

# get a list containing the last 3 elements of a
last_three = a[-3:]
print(last_three)

# reverse the list
reverse = a[::-1]
print(reverse)

# get a list where each entry in a is squared (so the new list is [1, 4, 9, 16, 25, 36])
squared = [number ** 2 for number in a]
print(squared)

[1, 2, 3, 4, 5, 6]
[4, 5, 6]
[6, 5, 4, 3, 2, 1]
[1, 4, 9, 16, 25, 36]


In [4]:
# create a numpy array from this list
b = np.array(a) # change this
print(b)

[1 2 3 4 5 6]


In [5]:
# find the mean of b
avg = np.mean(b)
print(avg)

3.5


In [6]:
# get a list where each entry in b is squared (so the new numpy array is [1, 4, 9, 16, 25, 36])
# use a different (numpy-specific) approach
b_squared = np.power(b, 2)
print(b_squared)

[ 1  4  9 16 25 36]


In [7]:
# change b from a length-6 list to a 2x3 matrix
b = np.reshape(b, (2, 3))
print(b)

[[1 2 3]
 [4 5 6]]


In [8]:
# find the mean value of each row
row_means = b.mean(axis=1)
print(row_means)

[2. 5.]


In [9]:
# find the mean value of each column
column_means = b.mean(axis=0)
print(column_means)

[2.5 3.5 4.5]


In [10]:
# find the third column of b
third_col = b[:,2]
print(third_col)

[3 6]


In [13]:
# load in the "starbucks.csv" dataset
import pandas as pd
import os
d = os.getcwd()
data = pd.read_csv('../data/starbucks.csv')
data

beverage_category                                    beverage  \
0                      coffee                               brewed coffee   
1                      coffee                               brewed coffee   
2                      coffee                               brewed coffee   
3                      coffee                               brewed coffee   
4     classic espresso drinks                                  caff latte   
..                        ...                                         ...   
237  frappuccino blended crme  strawberries  crme (without whipped cream)   
238  frappuccino blended crme        vanilla bean (without whipped cream)   
239  frappuccino blended crme        vanilla bean (without whipped cream)   
240  frappuccino blended crme        vanilla bean (without whipped cream)   
241  frappuccino blended crme        vanilla bean (without whipped cream)   

          beverage_prep  calories  total fat  trans fat  saturated fat  \
0                 Short         3        0.1        0.0            0.0   
1                  Tall         4        0.1        0.0            0.0   
2                Grande         5        0.1        0.0            0.0   
3                 Venti         5        0.1        0.0            0.0   
4     Short Nonfat Milk        70        0.1        0.1            0.0   
..                  ...       ...        ...        ...            ...   
237             Soymilk       320        3.2        0.4            0.0   
238    Tall Nonfat Milk       170        0.1        0.1            0.0   
239          Whole Milk       200        3.5        2.0            0.1   
240             Soymilk       180        1.5        0.2            0.0   
241  Grande Nonfat Milk       240        0.1        0.1            0.0   

     sodium  total carbohydrates  cholesterol  dietary fibre  sugars  protein  \
0         0                    5            0              0       0      0.3   
1         0                   10            0              0       0      0.5   
2         0                   10            0              0       0      1.0   
3         0                   10            0              0       0      1.0   
4         5                   75           10              0       9      6.0   
..      ...                  ...          ...            ...     ...      ...   
237       0                  250           67              1      64      5.0   
238       0                  160           39              0      38      4.0   
239      10                  160           39              0      38      3.0   
240       0                  160           37              1      35      3.0   
241       5                  230           56              0      55      5.0   

     vitamin a  vitamin c  calcium  iron  caffeine  
0            0          0        0   0.0     175.0  
1            0          0        0   0.0     260.0  
2            0          0        0   0.0     330.0  
3            0          0        2   0.0     410.0  
4           10          0       20   0.0      75.0  
..         ...        ...      ...   ...       ...  
237          6          8       20  10.0       0.0  
238          6          0       10   0.0       0.0  
239          6          0       10   0.0       0.0  
240          4          0       10   6.0       0.0  
241          8          0       15   0.0       0.0  

[242 rows x 18 columns]

In [14]:
# this is nutritional info for starbucks items
# let's see if we can answer some questions

# what is the average # calories across all items?
calories_list = data["calories"]
total = 0
for i in range(len(calories_list)):
    total += calories_list[i]
avg = total / len(calories_list)
print(avg)

193.87190082644628


In [15]:
# how many different categories of beverages are there?
beverage_categories = set()
bev_cat_list = data["beverage_category"]
for i in range(len(bev_cat_list)):
    beverage_categories.add(bev_cat_list[i])
num_bev_cat = len(beverage_categories)
print(num_bev_cat)
print(beverage_categories)

9
{'classic espresso drinks', 'smoothies', 'frappuccino blended crme', 'tazo tea drinks', 'signature espresso drinks', 'frappuccino light blended coffee', 'coffee', 'frappuccino blended coffee', 'shaken iced beverages'}


In [16]:
# what is the average # calories for each beverage category?
total_calories = {}
num_drinks_by_cat = {}
for i in range(len(calories_list)):
    if bev_cat_list[i] not in total_calories:
        total_calories.update({bev_cat_list[i]: calories_list[i]})
        num_drinks_by_cat.update({bev_cat_list[i]: 1})
    else:
        total_calories[bev_cat_list[i]] += calories_list[i]
        num_drinks_by_cat[bev_cat_list[i]] += 1
for key in total_calories:
    avg_calories = total_calories[key] / num_drinks_by_cat[key]
    print("The average number of calories in %s is %d" % (key, avg_calories))

The average number of calories in coffee is 4
The average number of calories in classic espresso drinks is 140
The average number of calories in signature espresso drinks is 250
The average number of calories in tazo tea drinks is 177
The average number of calories in shaken iced beverages is 114
The average number of calories in smoothies is 282
The average number of calories in frappuccino blended coffee is 276
The average number of calories in frappuccino light blended coffee is 162
The average number of calories in frappuccino blended crme is 233


In [17]:
# what beverage preparation includes the most sugar on average?
sugar_list = data["sugars"]
bev_prep_list = data["beverage_prep"]
total_sugar = {}
num_drinks_by_prep = {}
for i in range(len(sugar_list)):
    if bev_prep_list[i] not in total_sugar:
        total_sugar.update({bev_prep_list[i]: sugar_list[i]})
        num_drinks_by_prep.update({bev_prep_list[i]: 1})
    else:
        total_sugar[bev_prep_list[i]] += sugar_list[i]
        num_drinks_by_prep[bev_prep_list[i]] += 1
avg_sugar = {}
most_avg_sugar_key = bev_prep_list[0]
for key in total_sugar:
    bev_avg_sugar = total_sugar[key] / num_drinks_by_prep[key]
    avg_sugar.update({key: bev_avg_sugar})
    if bev_avg_sugar > avg_sugar[most_avg_sugar_key]:
        most_avg_sugar_key = key
print("The beverage preparation with the most sugar on average is %s with %d grams of sugar." % (most_avg_sugar_key, avg_sugar[most_avg_sugar_key]))

The beverage preparation with the most sugar on average is Whole Milk with 55 grams of sugar.


In [18]:
# what is the average % daily value calcium content for each beverage?
dv_calc = data["calcium"]
bev_list = data["beverage"]
total_calc = {}
num_drinks_by_bev = {}
for i in range(len(dv_calc)):
    if bev_list[i] not in total_calc:
        total_calc.update({bev_list[i]: dv_calc[i]})
        num_drinks_by_bev.update({bev_list[i]: 1})
    else:
        total_calc[bev_list[i]] += dv_calc[i]
        num_drinks_by_bev[bev_list[i]] += 1
for key in total_calc:
    avg_calc = total_calc[key] / num_drinks_by_bev[key]
    print("The average percent daily value calcium content in %s is %d" % (key, avg_calc))

The average percent daily value calcium content in brewed coffee is 0
The average percent daily value calcium content in caff latte is 35
The average percent daily value calcium content in caff mocha (without whipped cream) is 30
The average percent daily value calcium content in vanilla latte (or other flavoured latte) is 32
The average percent daily value calcium content in caff americano is 1
The average percent daily value calcium content in cappuccino is 22
The average percent daily value calcium content in espresso is 0
The average percent daily value calcium content in skinny latte (any flavour) is 33
The average percent daily value calcium content in caramel macchiato is 28
The average percent daily value calcium content in white chocolate mocha (without whipped cream) is 41
The average percent daily value calcium content in hot chocolate (without whipped cream) is 35
The average percent daily value calcium content in caramel apple spice (without whipped cream) is 0
The average

In [57]:
# It's bulking season. What drink should Naitian get so that he maximizes protein but minimizes calories?
# (you can use more than one line for this one)
# there are multiple valid approaches you can take for this (with different answers)
# I know that you want more calories for bulking season but whatever this is MDST, not Michigan Muscle Club okay
bevs = data.groupby("beverage")
df1 = bevs[['protein','calories']].agg({"calories": "mean", "protein": "mean"})
max_protein_to_calorie_ratio = 0
name_of_bev = ""
for i in range(len(df1.index)):
    p_c_ratio = df1.iloc[i]['protein']/df1.iloc[i]['calories']
    if(p_c_ratio > max_protein_to_calorie_ratio):
        max_protein_to_calorie_ratio = p_c_ratio
        name_of_bev = df1.iloc[i]
print("Naitian should drink ")

Naitian should drink 


/Users/isabelwang/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:10: RuntimeWarning: invalid value encountered in double_scalars
  # Remove the CWD from sys.path while we load stuff.


In [ ]:
# plot the distribution of the number of calories in drinks using matplotlib
import matplotlib.pyplot as plt

In [ ]:
# plot the same distribution using seaborn. what about a density plot instead?
import seaborn as sns

In [ ]:
# plot calories against total fat using seaborn


In [ ]:
# plot the distribution of calories in Short, Tall, Grande, and Venti drinks
# (you can use multiple lines for this)
# twist: you should also include the Nonfat Milk drinks that also have an associated size.

# you can decide how you want to visualize this. Colors? Small multiples? Density vs histogram?
# the starbucks is your oyster.
